### ISSUE TITLE
Missing questions

### ISSUE THREAD

**Issue by erlete** [erlete/algebruh#10]
There is missing data for some of the questions in the database. Said data must be added to the database whenever it is available.

_This issue is used as a reminder of the missing information, no need to do anything about it._

**Comment by erlete** [comment]
[This module](https://gist.github.com/erlete/ae0795cbe2c9efef88fd767fd8aeeb99) can be used to edit the question database. The `PATH_TO_DATABASE` constant needs to point to the `questions.json` file.

**Comment by Akanenosketch** [comment]
The last two questions have been added on the last PR sent.
